CREATE TABLE IF NOT EXISTS league_seasons_stage (
    league_id VARCHAR(32) NOT NULL,
    league_name VARCHAR(255) NOT NULL,
    league_type VARCHAR(64) NOT NULL,
    league_logo VARCHAR(512) NOT NULL,
    country_name VARCHAR(128) NOT NULL,
    country_code VARCHAR(16),
    country_flag VARCHAR(512),
    season_year INT NOT NULL,
    season_start VARCHAR(32),
    season_end VARCHAR(32),
    season_current BOOLEAN NOT NULL,
    cov_fixtures_events BOOLEAN NOT NULL,
    cov_fixtures_lineups BOOLEAN NOT NULL,
    cov_fixtures_stats_fixtures BOOLEAN NOT NULL,
    cov_fixtures_stats_players BOOLEAN NOT NULL,
    cov_standings BOOLEAN NOT NULL,
    cov_players BOOLEAN NOT NULL,
    cov_top_scorers BOOLEAN NOT NULL,
    cov_top_assists BOOLEAN NOT NULL,
    cov_top_cards BOOLEAN NOT NULL,
    cov_injuries BOOLEAN NOT NULL,
    cov_predictions BOOLEAN NOT NULL,
    cov_odds BOOLEAN NOT NULL
);

